const restaurants = [
  {
    id: "1",
    name: "Spice Hub",
    cuisine: ["North Indian", "Chinese"],
    rating: 4.2,
    deliveryTime: "30-35 mins",
    costForTwo: "₹400 for two",
    discount: "50% off up to ₹100",
    isVeg: false,
    image: "https://picsum.photos/seed/spicehub/400/300",
    location: "Sector 18, Noida",
    isOpen: true,
  },
  {
    id: "2",
    name: "Tandoori Tales",
    cuisine: ["Mughlai", "Kebabs"],
    rating: 4.5,
    deliveryTime: "25-30 mins",
    costForTwo: "₹600 for two",
    discount: "₹150 off above ₹499",
    isVeg: false,
    image: "https://picsum.photos/seed/tandoori/400/300",
    location: "Connaught Place, Delhi",
    isOpen: true,
  },
  {
    id: "3",
    name: "Green Bowl",
    cuisine: ["Healthy", "Salads"],
    rating: 4.0,
    deliveryTime: "20-25 mins",
    costForTwo: "₹300 for two",
    discount: "30% off",
    isVeg: true,
    image: "https://picsum.photos/seed/greenbowl/400/300",
    location: "Kormangala, Bangalore",
    isOpen: true,
  },
  {
    id: "4",
    name: "Pizza Planet",
    cuisine: ["Italian", "Pizzas"],
    rating: 4.3,
    deliveryTime: "35-40 mins",
    costForTwo: "₹500 for two",
    discount: "40% off",
    isVeg: false,
    image: "https://picsum.photos/seed/pizzaplanet/400/300",
    location: "Baner, Pune",
    isOpen: false,
  },
  {
    id: "5",
    name: "Curry Express",
    cuisine: ["South Indian", "Biryani"],
    rating: 4.1,
    deliveryTime: "20-30 mins",
    costForTwo: "₹350 for two",
    discount: "₹75 off above ₹299",
    isVeg: false,
    image: "https://picsum.photos/seed/curryexpress/400/300",
    location: "Hitech City, Hyderabad",
    isOpen: true,
  },
  {
    id: "6",
    name: "Veggie Delight",
    cuisine: ["Pure Veg", "Thali"],
    rating: 4.4,
    deliveryTime: "15-20 mins",
    costForTwo: "₹250 for two",
    discount: "Flat 20% off",
    isVeg: true,
    image: "https://picsum.photos/seed/veggiedelight/400/300",
    location: "Chandni Chowk, Delhi",
    isOpen: true,
  },
  {
    id: "7",
    name: "Sushi Samurai",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.6,
    deliveryTime: "40-45 mins",
    costForTwo: "₹800 for two",
    discount: "15% off",
    isVeg: false,
    image: "https://picsum.photos/seed/sushi/400/300",
    location: "Bandra, Mumbai",
    isOpen: true,
  },
  {
    id: "8",
    name: "Bun & Patty",
    cuisine: ["Burgers", "American"],
    rating: 4.0,
    deliveryTime: "25-30 mins",
    costForTwo: "₹400 for two",
    discount: "Buy 1 Get 1 Free",
    isVeg: false,
    image: "https://picsum.photos/seed/burger/400/300",
    location: "MG Road, Gurgaon",
    isOpen: false,
  },
  {
    id: "9",
    name: "Chatori Chatkara",
    cuisine: ["Street Food", "Snacks"],
    rating: 3.9,
    deliveryTime: "15-20 mins",
    costForTwo: "₹150 for two",
    discount: "₹50 off above ₹199",
    isVeg: true,
    image: "https://picsum.photos/seed/streetfood/400/300",
    location: "Charminar, Hyderabad",
    isOpen: true,
  },
  {
    id: "10",
    name: "Pasta Fiesta",
    cuisine: ["Italian", "Pasta"],
    rating: 4.2,
    deliveryTime: "30-35 mins",
    costForTwo: "₹450 for two",
    discount: "Flat 25% off",
    isVeg: false,
    image: "https://picsum.photos/seed/pasta/400/300",
    location: "Indiranagar, Bangalore",
    isOpen: true,
  },
  {
    id: "11",
    name: "Roller’s Joint",
    cuisine: ["Rolls", "Fast Food"],
    rating: 4.1,
    deliveryTime: "20-25 mins",
    costForTwo: "₹250 for two",
    discount: "₹100 off above ₹299",
    isVeg: false,
    image: "https://picsum.photos/seed/rolls/400/300",
    location: "Park Street, Kolkata",
    isOpen: true,
  },
  {
    id: "12",
    name: "Biryani Bliss",
    cuisine: ["Hyderabadi", "Biryani"],
    rating: 4.5,
    deliveryTime: "35-40 mins",
    costForTwo: "₹550 for two",
    discount: "Flat 20% off",
    isVeg: false,
    image: "https://picsum.photos/seed/biryani/400/300",
    location: "Secunderabad, Hyderabad",
    isOpen: true,
  },
  {
    id: "13",
    name: "Wok n Box",
    cuisine: ["Chinese", "Thai"],
    rating: 4.0,
    deliveryTime: "30-35 mins",
    costForTwo: "₹350 for two",
    discount: "₹75 off above ₹249",
    isVeg: false,
    image: "https://picsum.photos/seed/wok/400/300",
    location: "Viman Nagar, Pune",
    isOpen: false,
  },
  {
    id: "14",
    name: "Sweet Cravings",
    cuisine: ["Desserts", "Bakery"],
    rating: 4.3,
    deliveryTime: "20-25 mins",
    costForTwo: "₹300 for two",
    discount: "Buy 2 Get 1 Free",
    isVeg: true,
    image: "https://picsum.photos/seed/dessert/400/300",
    location: "Gariahat, Kolkata",
    isOpen: true,
  },
  {
    id: "15",
    name: "Kebab-e-Khaas",
    cuisine: ["Mughlai", "North Indian"],
    rating: 4.4,
    deliveryTime: "35-40 mins",
    costForTwo: "₹700 for two",
    discount: "₹200 off above ₹699",
    isVeg: false,
    image: "https://picsum.photos/seed/kebab/400/300",
    location: "Hazratganj, Lucknow",
    isOpen: true,
  },
  {
    id: "16",
    name: "Breakfast Junction",
    cuisine: ["South Indian", "Breakfast"],
    rating: 4.1,
    deliveryTime: "15-20 mins",
    costForTwo: "₹200 for two",
    discount: "Flat 10% off",
    isVeg: true,
    image: "https://picsum.photos/seed/breakfast/400/300",
    location: "T Nagar, Chennai",
    isOpen: true,
  },
  {
    id: "17",
    name: "Taco Town",
    cuisine: ["Mexican", "Tacos"],
    rating: 4.2,
    deliveryTime: "25-30 mins",
    costForTwo: "₹450 for two",
    discount: "Buy 1 Get 1 Free",
    isVeg: false,
    image: "https://picsum.photos/seed/taco/400/300",
    location: "Vashi, Navi Mumbai",
    isOpen: false,
  },
  {
    id: "18",
    name: "Noodle Nest",
    cuisine: ["Chinese", "Noodles"],
    rating: 3.8,
    deliveryTime: "20-25 mins",
    costForTwo: "₹250 for two",
    discount: "₹50 off above ₹149",
    isVeg: false,
    image: "https://picsum.photos/seed/noodles/400/300",
    location: "DLF Phase 3, Gurgaon",
    isOpen: true,
  },
  {
    id: "19",
    name: "Royal Thali",
    cuisine: ["Rajasthani", "Gujarati"],
    rating: 4.5,
    deliveryTime: "30-35 mins",
    costForTwo: "₹500 for two",
    discount: "Flat 20% off",
    isVeg: true,
    image: "https://picsum.photos/seed/thali/400/300",
    location: "CG Road, Ahmedabad",
    isOpen: true,
  },
  {
    id: "20",
    name: "The Coffee Spot",
    cuisine: ["Cafe", "Beverages"],
    rating: 4.0,
    deliveryTime: "15-20 mins",
    costForTwo: "₹350 for two",
    discount: "₹100 off above ₹299",
    isVeg: true,
    image: "https://picsum.photos/seed/coffee/400/300",
    location: "Brigade Road, Bangalore",
    isOpen: true,
  },
];
export default restaurants;